name: Deploy to GitHub Pages
# Run workflow on every push to the master branch
on:
  push:
    branches: [ master ]
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code form the master branch
    - uses: actions/checkout@v2
    # sets up .NET 6.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnetcore-version: 6.0.1
    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish sweetandsalty.web.csproj -c Release -o release --nologo
